<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net35</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>BroforceBugFix</RootNamespace>
    <AssemblyName>BroforceBugFix</AssemblyName>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <PackageModPath>$(MSBuildProjectDirectory)\BroforceBugFix</PackageModPath>
    <OutputPath>$(PackageModPath)\</OutputPath>
  </PropertyGroup>

  <Import Project="LocalBroforcePath.props" Condition="Exists('LocalBroforcePath.props')" />

  <PropertyGroup>
    <LocalBroforceModPath Condition="'$(UnityModManagerPath)' != ''">$(UnityModManagerPath)\..\Mods\GJKen-BroforceBugFix</LocalBroforceModPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>$(BroforceManagedPath)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(BroforceManagedPath)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(BroforceManagedPath)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityModManager">
      <HintPath>$(UnityModManagerPath)\UnityModManager.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(UnityModManagerPath)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(BroforceManagedPath)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="src\Plugin.cs" />
    <Compile Include="src\BugFixSettings.cs" />
    <Compile Include="src\DoodadCrateReentryFix.cs" />
  </ItemGroup>

  <Target Name="DeployBroforceBugFix" AfterTargets="Build" Condition="'$(TargetPath)' != ''">
    <MakeDir Directories="$(PackageModPath)" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\modinfo.json" DestinationFiles="$(PackageModPath)\Info.json" />
    <ItemGroup>
      <DeployBroforceBugFixPath Include="$(LocalBroforceModPath)" Condition="'$(LocalBroforceModPath)' != ''" />
      <DeployBroforceBugFixPath Include="$(TestDeployModPath)" Condition="'$(TestDeployModPath)' != ''" />
    </ItemGroup>
    <MakeDir Directories="@(DeployBroforceBugFixPath)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="%(DeployBroforceBugFixPath.Identity)" SkipUnchangedFiles="false" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\modinfo.json" DestinationFiles="%(DeployBroforceBugFixPath.Identity)\Info.json" />
  </Target>
</Project>
